[theme]
primaryColor = "#C3979F"
backgroundColor = "#CCDDB7"
secondaryBackgroundColor = "#545775"
textColor = "#34252f"
font = "serif"

[theme]
pageTitle = "Care Connect"
pageIcon = "ü§ù"

[theme]
layout = "center"
initialSidebarState = "auto"
